# Installation Instructions
# Centralized repository of all verbose installation instructions
# Used by setup modules to keep code clean and instructions consistent

INSTRUCTIONS = {
    'nodejs_installation': [
        "📋 INSTALLATION REQUIRED:",
        "   1. Go to https://nodejs.org/",
        "   2. Download the LTS version (version 18 or later)",
        "   3. Run the downloaded installer",
        "      - Accept all default settings unless you know what you're doing",
        "",
        "   4. After installation, open a terminal and run the following commands to verify:",
        "      - `node -v` (should return a version like v18.x.x or higher)",
        "      - `npm -v` (should return a version number)",
        "",
        "   5. Once installed, please re-run start_game.bat",
        "",
        "💡 This usually takes 2–3 minutes to download and install.",
        "💡 You'll need to restart your command prompt after installation."
        "",
        "",
        "You have the following options to continue:",
        "   1. Skip and move on to next component (recommended)",
        "   2. Try to install frontend dependencies anyways (if nodejs is installed, but undetected)",
        "   3. Exit the setup and restart when nodejs is installed",
        ""
    ],

    'mysql_installation': [
        "📋 MYSQL INSTALLATION REQUIRED:",
        "",
        "1. Go to https://dev.mysql.com/downloads/mysql/",
        "2. Click 'MySQL Community Server'",
        "3. Select your Windows version (Windows 10/11)",
        "4. Download the MSI Installer (mysql-installer-community-x.x.xx.msi)",
        "",
        "5. Run the installer as Administrator:",
        "   - Choose 'Developer Default' or 'Server only'",
        "   - Keep default port 3306",
        "   - Set a root password (WRITE THIS DOWN!)",
        "   - Choose 'Configure MySQL Server as a Windows Service'",
        "   - Service name: MySQL80 (or MySQL84)",
        "   - Start the MySQL Server at System Startup: YES",
        "",
        "6. Complete the installation (may take 5-10 minutes)",
        "7. Test installation: Open Command Prompt and run 'mysql --version'",
        "",
        "💡 Installation size: ~200MB",
        "💡 You'll need the root password for database setup later!",
        "",
        "If the installer fails, try:",
        "- Running as Administrator",
        "- Temporarily disabling antivirus",
        "- Using the ZIP archive instead of MSI installer"
    ],

    'mysql_service_start': [
        "📋 STARTING MYSQL SERVICE MANUALLY:",
        "",
        "Method 1 - Services Manager (Recommended):",
        "1. Press Win+R, type 'services.msc', press Enter",
        "2. Scroll down and find 'MySQL80' or 'MySQL84' or 'MySQL'",
        "3. Right-click the service → 'Start'",
        "4. If you want it to start automatically:",
        "   - Right-click → 'Properties'",
        "   - Change 'Startup type' to 'Automatic'",
        "   - Click 'OK'",
        "",
        "Method 2 - Command Line (Run as Administrator):",
        "1. Right-click Start menu → 'Windows Terminal (Admin)'",
        "2. Type: net start MySQL80",
        "3. Or try: net start MySQL84",
        "4. Or try: net start MySQL",
        "",
        "Method 3 - MySQL Workbench:",
        "1. Open MySQL Workbench (if installed)",
        "2. Click 'Server Status' in the sidebar",
        "3. Click 'Start Server'",
        "",
        "If all methods fail:",
        "- Check Windows Event Viewer for MySQL errors",
        "- MySQL may have configuration issues",
        "- Consider reinstalling MySQL"
    ],

    'mysql_troubleshooting': [
        "📋 MYSQL TROUBLESHOOTING:",
        "",
        "Common issues and solutions:",
        "",
        "Issue 1 - Port 3306 in use:",
        "1. Open Command Prompt as Administrator",
        "2. Run: netstat -ano | findstr :3306",
        "3. If another process is using port 3306:",
        "   - Stop that process, or",
        "   - Reconfigure MySQL to use a different port",
        "",
        "Issue 2 - MySQL won't start:",
        "1. Check Windows Event Viewer:",
        "   - Press Win+R → eventvwr.msc",
        "   - Go to Windows Logs → Application",
        "   - Look for MySQL errors",
        "2. Common fixes:",
        "   - Delete ib_logfile0 and ib_logfile1 from MySQL data directory",
        "   - Run MySQL as Administrator",
        "   - Check disk space (MySQL needs space for logs)",
        "",
        "Issue 3 - Permission errors:",
        "1. Run Command Prompt as Administrator",
        "2. Navigate to MySQL bin directory",
        "3. Try: mysqld --install",
        "4. Then: net start mysql",
        "",
        "Issue 4 - Configuration problems:",
        "1. Locate my.ini file (usually in MySQL installation folder)",
        "2. Check for syntax errors",
        "3. Reset to default configuration if needed",
        "",
        "Last resort:",
        "- Completely uninstall MySQL",
        "- Delete all MySQL folders",
        "- Reinstall with default settings"
    ],

    'mysql_cli_path': [
        "📋 ADDING MYSQL CLI TO SYSTEM PATH:",
        "",
        "Your MySQL installation was detected. Follow these steps:",
        "",
        "1. Copy the MySQL bin path shown above",
        "2. Press Win+R, type 'sysdm.cpl', press Enter",
        "3. Click 'Environment Variables' button",
        "4. In 'System Variables' section (bottom), find 'Path'",
        "5. Select 'Path' and click 'Edit'",
        "6. Click 'New' button",
        "7. Paste the MySQL bin path",
        "8. Click 'OK' on all dialogs",
        "",
        "9. IMPORTANT: Close all Command Prompt windows",
        "10. Open a new Command Prompt",
        "11. Test by running: mysql --version",
        "",
        "Alternative method (Windows 10/11):",
        "1. Right-click 'This PC' → Properties",
        "2. Click 'Advanced system settings'",
        "3. Follow steps 3-11 above",
        "",
        "If it still doesn't work:",
        "- Make sure you closed ALL command prompt windows",
        "- Try restarting your computer",
        "- Verify the path exists and contains mysql.exe"
    ],

    'mysql_cli_path_generic': [
        "📋 ADDING MYSQL CLI TO SYSTEM PATH:",
        "",
        "MySQL CLI not found in PATH. To fix this:",
        "",
        "1. Find your MySQL installation:",
        "   - Check: C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin",
        "   - Check: C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin", 
        "   - Check: C:\\xampp\\mysql\\bin",
        "   - Check: C:\\wamp64\\bin\\mysql\\mysql8.x.x\\bin",
        "",
        "2. Once you find the folder containing mysql.exe:",
        "   - Copy the full path to that folder",
        "",
        "3. Add to System PATH:",
        "   - Press Win+R, type 'sysdm.cpl', press Enter",
        "   - Click 'Environment Variables'",
        "   - In 'System Variables', find 'Path' and click 'Edit'",
        "   - Click 'New' and paste the MySQL bin path",
        "   - Click 'OK' on all dialogs",
        "",
        "4. Test the fix:",
        "   - Close all Command Prompt windows",
        "   - Open new Command Prompt",
        "   - Run: mysql --version",
        "",
        "If you can't find MySQL installation:",
        "- MySQL may not be properly installed",
        "- Try reinstalling MySQL with default settings",
        "- Make sure to include 'MySQL Command Line Client' during installation"
    ],

    'database_password_setup': [
        "📋 DATABASE PASSWORD SETUP:",
        "",
        "The game needs your MySQL root password to connect to the database.",
        "This is the password you set when installing MySQL.",
        ""
    ],

    'database_connection_troubleshooting': [
        "📋 START MYSQL SERVER:",
        "",
        "Your MySQL server needs to be running for the game to work.",
        "Here's how to start it:",
        "",
        "Method 1 - Windows Services (Recommended):",
        "1. Press Win+R, type 'services.msc', press Enter",
        "2. Look for 'MySQL80' or 'MySQL84' or 'MySQL'",
        "3. If status shows 'Stopped', right-click → 'Start'",
        "4. Status should change to 'Running'",
        "",
        "Method 2 - Command Line:",
        "1. Open Command Prompt as Administrator",
        "2. Try: net start MySQL80",
        "3. Or try: net start MySQL84", 
        "4. Or try: net start MySQL",
        "5. You should see: 'The MySQL service was started successfully'",
        "",
        "Method 3 - MySQL Workbench:",
        "1. Open MySQL Workbench (if installed)",
        "2. Look for 'Server Status' or 'Server Administration'",
        "3. Click 'Start Server'",
        "",
        "💡 MySQL server must be running every time you play the game"
    ],

    'database_troubleshooting': [
        "📋 GENERAL DATABASE TROUBLESHOOTING:",
        "",
        "Connection issues can have several causes:",
        "",
        "Issue 1 - Firewall blocking connection:",
        "1. Check Windows Firewall settings",
        "2. Allow MySQL through firewall (port 3306)",
        "3. Or temporarily disable firewall to test",
        "",
        "Issue 2 - MySQL configuration problems:",
        "1. Find my.ini file (usually in MySQL installation folder)",
        "2. Check bind-address setting (should be 0.0.0.0 or commented)",
        "3. Restart MySQL service after changes",
        "",
        "Issue 3 - User permissions:",
        "1. Connect to MySQL as root",
        "2. Check user permissions: SHOW GRANTS FOR 'root'@'localhost';",
        "3. Grant permissions if needed: GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';",
        "",
        "Issue 4 - Wrong host/port in .env:",
        "1. Check .env file has correct settings:",
        "   DB_HOST=localhost",
        "   DB_PORT=3306",
        "2. Verify MySQL is actually running on these",
        "",
        "Issue 5 - MySQL version compatibility:",
        "1. Check MySQL version: mysql --version",
        "2. Older versions may have different authentication",
        "3. Try: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_password';",
        "",
        "Last resort - Reinstall MySQL:",
        "1. Uninstall MySQL completely",
        "2. Delete all MySQL folders and data",
        "3. Reinstall with default settings"
    ],

    'database_manual_creation': [
        "📋 MANUAL DATABASE CREATION:",
        "",
        "Create the game database manually using one of these methods:",
        "",
        "Method 1 - MySQL Workbench (Easiest):",
        "1. Open MySQL Workbench",
        "2. Connect to your local MySQL server",
        "3. In the query tab, run:",
        "   CREATE DATABASE IF NOT EXISTS monster_hunter_game;",
        "4. Click the lightning bolt to execute",
        "5. Verify: You should see 'monster_hunter_game' in the schemas panel",
        "",
        "Method 2 - Command Line:",
        "1. Open Command Prompt",
        "2. Connect to MySQL:",
        "   mysql -u root -p",
        "3. Enter your MySQL root password",
        "4. Create database:",
        "   CREATE DATABASE IF NOT EXISTS monster_hunter_game;",
        "5. Verify:",
        "   SHOW DATABASES;",
        "   (You should see 'monster_hunter_game' in the list)",
        "6. Exit: EXIT;",
        "",
        "Method 3 - phpMyAdmin (if you have XAMPP/WAMP):",
        "1. Open phpMyAdmin in browser",
        "2. Click 'Databases' tab",
        "3. Enter 'monster_hunter_game' as database name",
        "4. Click 'Create'",
        "",
        "To test the database was created:",
        "1. Run this setup again",
        "2. Or manually test: mysql -u root -p -e \"USE monster_hunter_game; SELECT 1;\"",
        "",
        "💡 Database name must be exactly: monster_hunter_game",
        "💡 The game will create tables automatically when first run"
    ]
}

def get_instructions(key):
    """
    Get installation instructions by key
    
    Args:
        key (str): Instruction key from INSTRUCTIONS dict
        
    Returns:
        list: List of instruction lines, or empty list if key not found
    """
    return INSTRUCTIONS.get(key, [])

def get_available_instructions():
    """
    Get list of all available instruction keys
    
    Returns:
        list: All instruction keys
    """
    return list(INSTRUCTIONS.keys())